# GoReleaser configuration
before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

# Use simpler snapshot naming to ensure compatibility
snapshot:
  name_template: "next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

# Explicitly configure GitHub Releases
release:
  github:
    owner: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
    name: "{{.Env.GITHUB_REPOSITORY_NAME}}"
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
