FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the pre-built binary file from the GoReleaser build
COPY mcpenetes .

# Run the application
ENTRYPOINT ["./mcpenetes"] 
